import type { Metadata } from "next";
import { inter } from '@/app/ui/fonts';

import Navigation from '@/app/ui/naivgation';

export const metadata: Metadata = {
  title: "Presentación",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div>
          <Navigation />
        </div>
        <div className={`${inter.className} antialiased`} >
          {children}
        </div>
        <a id="abajo">Abajo</a>
      </body>
    </html>
  );
}
